import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'
import DesktopSidebar from '@/components/Sidebar/DesktopSidebar'
import Header from '@/components/Header'
import MobileSidebar from '@/components/Sidebar/MobileSidebar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-[#6A4DFC]/[20%]`}>
          <div className="flex h-full">
            <div className="hidden md:block">
              <DesktopSidebar />
            </div>
            <div className="md:hidden">
              <MobileSidebar />
            </div>
            <div className="flex-1 flex flex-col h-full overflow-hidden">
              <Header />
              <main>
                {children}
              </main>
            </div>
          </div>
          <Toaster position="top-right" richColors />
        </body>
      </html>
    </ClerkProvider>
  )
}